# Используем официальный образ Python с Django
FROM python:3.10

# Устанавливаем рабочую директорию
WORKDIR /app

# Устанавливаем зависимости из requirements_api.txt
COPY requirements_api.txt /app/
RUN pip install -r requirements_api.txt

# Копируем проект в контейнер
COPY . /app/

# Открываем порт для веб-приложения
EXPOSE 8000

# Команда для запуска сервера
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]