# Generated by Django 3.2.6 on 2023-09-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinuteAggregate',
            fields=[
                ('minute', models.DateTimeField(primary_key=True, serialize=False)),
                ('average_value', models.FloatField()),
            ],
            options={
                'db_table': 'minute_aggregate_view',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TimeLog',
        ),
    ]
